# Generated by Django 3.2.9 on 2021-11-23 08:24

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('lastname', models.CharField(max_length=30)),
                ('middlename', models.CharField(blank=True, max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.IntegerField(choices=[(0, 'Member'), (5, 'Manager'), (11, 'System Admin')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
